routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
| Middleware options can be located in `app/Http/Kernel.php`
|
*/

// Homepage Route
// Route::get('/', 'WelcomeController@welcome')->name('welcome');

// Authentication Routes
// Route::group(['middleware' => 'https'], function() {
    Auth::routes();
// });

// Public Routes
Route::group(['middleware' => 'web'], function() {

    // Activation Routes
    Route::get('/activate', ['as' => 'activate', 'uses' => 'Auth\ActivateController@initial']);
    Route::get('/forgot', ['as' => 'forgot', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);

    Route::get('/activate/{token}', ['as' => 'authenticated.activate', 'uses' => 'Auth\ActivateController@activate']);
    Route::get('/activation', ['as' => 'authenticated.activation-resend', 'uses' => 'Auth\ActivateController@resend']);
    Route::get('/exceeded', ['as' => 'exceeded', 'uses' => 'Auth\ActivateController@exceeded']);

    // Socialite Register Routes
    Route::get('/social/redirect/{provider}', ['as' => 'social.redirect', 'uses' => 'Auth\SocialController@getSocialRedirect']);
    Route::get('/social/handle/{provider}', ['as' => 'social.handle', 'uses' => 'Auth\SocialController@getSocialHandle']);

    // Route to for user to reactivate their user deleted account.
    Route::get('/re-activate/{token}', ['as' => 'user.reactivate', 'uses' => 'RestoreUserController@userReActivate']);

});

// Registered and Activated User Routes
Route::group(['middleware' => ['auth', 'activated']], function() {

    // Activation Routes
    Route::get('/activation-required', ['uses' => 'Auth\ActivateController@activationRequired'])->name('activation-required');
    Route::get('/logout', ['uses' => 'Auth\LoginController@logout'])->name('logout');

    //  Homepage Route - Redirect based on user role is in controller.
    Route::get('/home', ['as' => 'public.home',   'uses' => 'UserController@index']);

    // Show users profile - viewable by other users.
    Route::get('profile/{username}', [
        'as'        => '{username}',
        'uses'      => 'ProfilesController@show'
    ]);

});

// Registered, activated, and is current user routes.
Route::group(['middleware'=> ['auth', 'activated', 'currentUser']], function () {

    // User Profile and Account Routes
    Route::resource(
        'profile',
        'ProfilesController', [
            'only'  => [
                'show',
                'edit',
                'update',
                'create'
            ]
        ]
    );
    Route::put('profile/{username}/updateUserAccount', [
        'as'        => '{username}',
        'uses'      => 'ProfilesController@updateUserAccount'
    ]);
    Route::put('profile/{username}/updateUserPassword', [
        'as'        => '{username}',
        'uses'      => 'ProfilesController@updateUserPassword'
    ]);
    Route::delete('profile/{username}/deleteUserAccount', [
        'as'        => '{username}',
        'uses'      => 'ProfilesController@deleteUserAccount'
    ]);

    // Route to show user avatar
    Route::get('images/profile/{id}/avatar/{image}', [
        'uses'      => 'ProfilesController@userProfileAvatar'
    ]);

    // Route to upload user avatar.
    Route::post('avatar/upload', ['as' => 'avatar.upload', 'uses' => 'ProfilesController@upload']);

});

// Registered, activated, and is admin routes.
Route::group(['middleware'=> ['auth', 'activated']], function () {

    Route::get('users/reg',          ['uses' => 'UsersManagementController@reg', 'as'=>'user-reg']);

    Route::resource('/users/deleted', 'SoftDeletesController', [
        'only' => [
            'index', 'show', 'update', 'destroy',
        ]
    ]);

    Route::resource('users', 'UsersManagementController', [
        'names' => [
            'index' => 'users',
            'destroy' => 'user.destroy'
        ],
        'except' => [
            'deleted'
        ]
    ]);

    Route::resource('themes', 'ThemesManagementController', [
        'names' => [
            'index' => 'themes',
            'destroy' => 'themes.destroy'
        ]
    ]);

    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    Route::get('php', 'AdminDetailsController@listPHPInfo');
    Route::get('routes', 'AdminDetailsController@listRoutes');

});

app/Http/Controllers/UsersManagementController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Profile;
use App\Models\User;
use App\Traits\ActivationTrait;
use App\Traits\CaptchaTrait;
use App\Traits\CaptureIpTrait;
use Auth;
use Illuminate\Foundation\Auth\RegistersUsers;
use Illuminate\Http\Request;
use jeremykenedy\LaravelRoles\Models\Permission;
use jeremykenedy\LaravelRoles\Models\Role;
use Validator;
use DB;
use Input;

class UsersManagementController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        $roles = Role::all();

        return View('usersmanagement.show-users', compact('users', 'roles'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $roles = Role::all();

        $data = [
            'roles' => $roles
        ];

        return view('usersmanagement.create-user')->with($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $validator = Validator::make($request->all(),
            [
                'name'                  => 'required|max:255|unique:users',
                'first_name'            => '',
                'last_name'             => '',
                'email'                 => 'required|email|max:255|unique:users',
                'password'              => 'required|min:6|max:20|confirmed',
                'password_confirmation' => 'required|same:password',
                'role'                  => 'required'
            ],
            [
                'name.unique'           => trans('auth.userNameTaken'),
                'name.required'         => trans('auth.userNameRequired'),
                'first_name.required'   => trans('auth.fNameRequired'),
                'last_name.required'    => trans('auth.lNameRequired'),
                'email.required'        => trans('auth.emailRequired'),
                'email.email'           => trans('auth.emailInvalid'),
                'password.required'     => trans('auth.passwordRequired'),
                'password.min'          => trans('auth.PasswordMin'),
                'password.max'          => trans('auth.PasswordMax'),
                'role.required'         => trans('auth.roleRequired')
            ]
        );

        if ($validator->fails()) {

            $this->throwValidationException(
                $request, $validator
            );

        } else {

            $ipAddress  = new CaptureIpTrait;
            $profile    = new Profile;

            $user =  User::create([
                'name'              => $request->input('name'),
                'first_name'        => $request->input('first_name'),
                'last_name'         => $request->input('last_name'),
                'email'             => $request->input('email'),
                'password'          => bcrypt($request->input('password')),
                'token'             => str_random(64),
                'admin_ip_address'  => $ipAddress->getClientIp(),
                'activated'         => 1
            ]);

            $user->profile()->save($profile);
            $user->attachRole($request->input('role'));
            $user->save();

            return redirect('users')->with('success', trans('usersmanagement.createSuccess'));

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (Auth::user()->hasRole(['sadmin']) || $id == Auth::user()->id) {
        } else{
            return redirect()->back();
        }
        $user = User::find($id);

        return view('usersmanagement.show-user')->withUser($user);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $user = User::findOrFail($id);
        $roles = Role::all();

        foreach ($user->roles as $user_role) {
            $currentRole = $user_role;
        }

        $data = [
            'user'          => $user,
            'roles'         => $roles,
            'currentRole'   => $currentRole
        ];

        return view('usersmanagement.edit-user')->with($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $currentUser = Auth::user();
        $user        = User::find($id);
        $emailCheck  = ($request->input('email') != '') && ($request->input('email') != $user->email);
        $ipAddress   = new CaptureIpTrait;

        if ($emailCheck) {
            $validator = Validator::make($request->all(), [
                'name'      => 'required|max:255',
                'email'     => 'email|max:255|unique:users',
                'password'  => 'present|confirmed|min:6'
            ]);
        } else {
            $validator = Validator::make($request->all(), [
                'name'      => 'required|max:255',
                'password'  => 'nullable|confirmed|min:6'
            ]);
        }
        if ($validator->fails()) {
            $this->throwValidationException(
                $request, $validator
            );
        } else {
            $user->name = $request->input('name');

            if ($emailCheck) {
                $user->email = $request->input('email');
            }
            if ($request->input('password') != null) {
                $user->password = bcrypt($request->input('password'));
            }
            if ($request->input('first_name') != null) {
                $user->first_name= $request->input('first_name');
            }
            if ($request->input('last_name') != null) {
                $user->last_name = $request->input('last_name');
            }
            if ($request->input('r') != null) {
                $user->r = $request->input('r');
                $role=$request->input('r');
            }
            if ($request->input('t') != null) {
                $user->t = $request->input('t');
            }

            $role=$request->input('role')!=null?$request->input('role'):$role;
            $user->detachAllRoles();
            $user->attachRole($role);
            //$user->activated = 1;

            $user->updated_ip_address = $ipAddress->getClientIp();

            $user->save();
            // return back()->with('success', trans('usersmanagement.updateSuccess'));
            return 'ok';
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $currentUser = Auth::user();
        $user        = User::findOrFail($id);
        $ipAddress   = new CaptureIpTrait;

        if ($user->id != $currentUser->id) {

            $user->deleted_ip_address = $ipAddress->getClientIp();
            $user->save();
            $user->forceDelete();
            return redirect('users')->with('success', trans('usersmanagement.deleteSuccess'));
        }
        return back()->with('error', trans('usersmanagement.deleteSelfError'));
    }

    function reg()
    {   
        $user  = User::where('id', '=', Input::get('uid'))->first();
        $roles = Role::all();
        $profile = DB::select('SELECT * FROM profiles where user_id=?', [Input::get('uid')]);
        $travels=DB::select('SELECT idkbih i, kbihname n FROM db_ibadah.mt_kbih where IsFlag=0');

        if ($profile) {
            $profile=$profile[0];
        }
        return view('usersmanagement._register',compact('roles','travels','user','profile'));
    }
}

resources/views/usersmanagement/_register.blade.php
<div class="card">
	<div class="card-header card-header-icon" data-background-color="blue">
		<i class="material-icons">mode_edit</i>
	</div>
	<span class="btn card-header card-header-icon round pull-right rp-close" data-background-color="red">
		<i class="material-icons">close</i>
	</span>
	<div class="card-content">
		<h4 class="card-title">{{ $user ? 'Ubah pengguna : '.$user->name : 'Tambah Pengguna Baru' }}</h4>
		<div class="card-content-overflow">
			<form id="freg">
				<input type="hidden" name="id" data-id="{{ $user ? $user->id: 0 }}">
				<div class="form-group label-floating">
					<label class="control-label">Nama Pengguna</label>
					<input type="text" class="form-control" name="name" value="{{ $user ? $user->name : '' }}" {{ $user?'readonly':'' }}>
				</div>
				<div class="form-group label-floating">
					<label class="control-label">Email</label>
					<input type="text" class="form-control" name="email" value="{{ $user ? $user->email : '' }}" {{ $user?'readonly':'' }}>
				</div>
				<div class="form-group label-floating">
					<label class="control-label">Nama Depan</label>
					<input type="text" class="form-control" name="first_name" value="{{ $user ? $user->first_name : '' }}">
				</div>
				<div class="form-group label-floating">
					<label class="control-label">Nama Belakang</label>
					<input type="text" class="form-control" name="last_name" value="{{ $user ? $user->last_name : '' }}">
				</div>
				<div class="form-group label-floating">
					<label class="control-label">User role / Peran Pengguna</label>
					<select class="selectpicker" data-style="select-with-transition" name="r" id="role">
						@foreach($roles as $role)
							<option value="{{ $role->id }}" {{ ($user ? $user->r : 0) == $role->id ? 'selected="selected"' : '' }}>{{ $role->name }}</option>
						@endforeach
					</select>
				</div>
				<div class="form-group label-floating" id="tra" hidden>
					<label class="control-label">Agen Travel</label>
					<select class="selectpicker" data-style="select-with-transition" name="t" id="travel">
						<option value="0" disabled> Pilih agen perjalanan</option>
						@foreach($travels as $travel)
							<option value="{{ $travel->i }}" {{ ($user ? $user->t : 0) == $travel->i ? 'selected="selected"' : '' }}>{{ $travel->n }}</option>
						@endforeach
					</select>
				</div>
				<div class="form-group label-floating" hidden>
					<label class="control-label">Kata Sandi</label>
					<input type="password" class="form-control" name="password" id="p1">
				</div>
				<div class="form-group label-floating" hidden>
					<label class="control-label">Konfirmasi Kata Sandi</label>
					<input type="password" class="form-control" name="password_confirmation" id="p2">
				</div>
			</form>
		</div>
	</div>
	<div class="card-footer">
		<div class="pull-right">
			<button id="sfreg" type="submit" class="btn btn-fill btn-rose">Simpan</button>
		</div>				
	</div>
</div>

<script>
	$('.selectpicker').selectpicker();

	$('#role').change(function(e) {
		e.preventDefault()
		// console.log($(this).val())
		// if role == travel
		if ($(this).val()==2) {
			$('#tra').slideDown()
		} else {
			$('#tra').slideUp()
		}
	})
	$('#role').change()

	$('#sfreg').click(function(e) {
		e.preventDefault()
        var $validator = $('.card-content-overflow form').validate({
            rules: {
                name: {
                    required: true,
                    contentSpecialCharacters: true
                },
                first_name: {
                    required: true,
                    contentSpecialCharacters: true
                },
                last_name: {
                    required: true,
                    contentSpecialCharacters: true
                },
                email: {
                    required: true,
                    email5: true
                },

            },
            messages: {
                name: "Wajib diisi / Spesial Karakter Tidak Diperbolehkan",

            },
            errorPlacement: function(error, element) {
                $(element).parent('div').addClass('has-error');
                $(element).parent('div').append(error);

            }

        });
        var $valid = $('.card-content-overflow form').valid();
        if(!$valid) {
            $validator.focusInvalid();
            return false;
        }
        swal({
            title: 'Apakah Anda Yakin?',
            type: 'question',
            showCancelButton: true,
            confirmButtonText: 'Ya',
            cancelButtonText: 'Batal'
        }).then(function () {
        swal('Mohon Menunggu')
        swal.showLoading()

        uploadnupdate()

        if ($('input[name=id]').data('id')==0) {
	        $('#p1').val(Math.random().toString(36).substring(5))
	        $('#p2').val($('#p1').val())
			data=$("#freg").serialize();
		    // console.log('data',data)
		    saveusr(data)
        } else {
			data=$("#freg").serialize();
		    editusr(data)
        }


	})

	function saveusr(data) {
		$.post("{{ url('register') }}", data, function(r) {
	        console.log(r.status)
	        if(r.status!='ok'){
	            swal(
	                'Terjadi Kesalahan',
	                'Mohon Dicek Kembali',
	                'error'
	            )
	        } else {
		        swal(
		            'Berhasil',
		            '',
		            'success'
		        ).then(function() {
		            $('#rp').empty().slideReveal("hide")
		            location.reload(true)
		        })
	        }
	    }, 'json').fail(function(response) {
	        // console.log(response)
	        swal(
	            'Terjadi kesalahan! ',
	            //response.responseText,
				'Mohon Dicek Kembali',
	            'error'
	        )
	    }); 
	}

	function editusr(data) {
		var url='{{ route('users.update', ":usr") }}'
		url = url.replace(':usr', '{{ $user?$user->id:0 }}')
		$.ajax({
		    url: url,
		    type: 'PUT',
		    data:data,
		    success: function(r) {
		        console.log(r)
		        if(r!='ok'){
		            swal(
		                'Terjadi kesalahan!',
		                'Mohon Dicek Kembali.',
		                'error'
		            )
		        } else {
			        swal(
			            'Berhasil',
			            '',
			            'success'
			        ).then(function() {
		            	$('#rp').empty().slideReveal("hide")
		           		location.reload(true)
			        })
		        }
		    },				    
		}).fail(function(response){
			console.log(response)
	        swal(
	            'Terjadi Kesalahan!',
	            //response.responseText,
				'Mohon Dicek Kembali',
	            'error'
	        )			    	
		})
	}

	function uploadnupdate() {
        swal('Mohon Menunggu')
        swal.showLoading()

        old1 = $("#img").data('old')
        var form_data = new FormData();
        form_data.append("file", $("#img").prop("files")[0])
        form_data.append("dir", 'avatar')
        form_data.append("w", 800)
        form_data.append("h", 800)

        $.ajax({
            url: "{{route('cms-upload') }}",
            cache: false,
            contentType: false,
            processData: false,
            data: form_data,
            type: 'post',
            success: function (p) {
                if (!p.p1) {
                    if (old1 != p.p1) {
                        p.p1 = old1;
                    }
                }
                data = {
                    idp: $('input[name=id]').data('id'),
                    p1: p.p1
                }
                $.post("{{route('update-profile') }}", data, function (r) {
                }, 'json').fail(function (response) {
                    console.log(response)
                    swal(
                        'Terjadi kesalahan!',
                        //response.responseText,
						'Mohon Dicek Kembali.',
                        'error'
                    )
                });
            }
        })
    }
	})

</script>

resources/views/usersmanagement/show-user.blade.php
@extends('Dts::layouts.dts')

@section('h-title')
  {{ $user->name }}
@endsection

@section('title')
  Tampilkan Pengguna {{ $user->name }}
@endsection

@section('content')
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="card card-profile">
					<div class="card-content">
						@if ($user->id == Auth::user()->id)
							<div class="fileinput fileinput-new text-center pull-right" data-provides="fileinput">
								<div class="fileinput-new thumbnail img-circle">
									<img src="{{ $user->profile ? asset('storage/'.$user->profile->avatar) : asset('images/placeholder.jpg') }}">
								</div>
								<div class="fileinput-preview fileinput-exists thumbnail img-circle"></div>
								<div>
									<span class="btn btn-rose btn-round btn-file">
									<span class="fileinput-new">Pilih gambar</span>
									<span class="fileinput-exists">Ganti</span>
										<input type="file" name="img" id="img" data-old="{{ $user->profile ? asset('storage/'.$user->profile->avatar) : '' }}" />
									</span>
									<a href="#pablo" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput"><i class="fa fa-times"></i> Hapus</a>
								</div>
							</div>
						@endif
						@if ($user->id != Auth::user()->id)
							<div class="fileinput fileinput-new text-center pull-right" data-provides="fileinput">
								<div class="fileinput-new thumbnail img-circle">
									<img src="{{ $user->profile ? asset('storage/'.$user->profile->avatar) : asset('images/placeholder.jpg') }}">
								</div>
							</div>
						@endif

						<a href="{{ url()->previous() }}" class="btn btn-sm btn-info">
							<i class="fa fa-chevron-left fa-fw" aria-hidden="true"></i>&nbsp;
							<span class="hidden-xs hidden-sm"> Kembali</span>
						</a>
						<h4 class="card-title">Informasi Pengguna</h4>
						<form id="f-pw">
							<div class="row">
								<div class="col-md-3">
									<div class="form-group label-floating">
										@php
											if ($user->activated == 1) {
												$status='Terverifikasi';
											}else{
												$status='Belum Terverifikasi';
											}
										@endphp
										<label class="control-label">Status</label>
										<input type="text" class="form-control" value="{{ $status }}" readonly>
									</div>
								</div>
								<div class="col-md-3">
									<div class="form-group label-floating">
										<label class="control-label">User role / Peran Pengguna</label>
										<input type="text" class="form-control" value="{{ $user->roles[0]->name }}" readonly>
										<input type="text" name='role' value="{{ $user->roles[0]->id }}" hidden>
									</div>
								</div>
								@if ($user->roles[0]->id == 2)
									@php
									    $agen=DB::select('SELECT KbihName FROM db_ibadah.mt_kbih where IdKbih=?',[$user->t])[0];
									@endphp
									<div class="col-md-3">
										<div class="form-group label-floating">
											<label class="control-label">Agen Travel</label>
											<input type="text" class="form-control" value="{{ $agen->KbihName }}" readonly>
										</div>
									</div>
								@endif
							</div>
							<div class="row">
								<div class="col-md-6">
									<div class="form-group label-floating">
										<label class="control-label">Nama Pengguna</label>
										<input type="text" class="form-control" name="name" value="{{ $user->name }}" readonly>
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group label-floating">
										<label class="control-label">Email</label>
										<input type="text" class="form-control" name="email" value="{{ $user->email }}" readonly>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-6">
									<div class="form-group label-floating">
										<label class="control-label">Nama Depan</label>
										<input type="text" class="form-control" value="{{ $user->first_name }}" readonly>
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group label-floating">
										<label class="control-label">Nama Belakang</label>
										<input type="text" class="form-control" value="{{ $user->last_name }}" readonly>
									</div>
								</div>
							</div>

							<div class="clearfix"></div>

							@if ($user->id == Auth::user()->id)
								<div class="row">
									<div id="pw" hidden>
										<div class="col-md-3">
											<div class="form-group label-floating" >
												<label class="control-label">Kata Sandi</label>
												<input type="password" class="form-control" name="password" id="p1">
											</div>
										</div>
										<div class="col-md-3">
											<div class="form-group label-floating" >
												<label class="control-label">Konfirmasi Kata Sandi</label>
												<input type="password" class="form-control" name="password_confirmation" id="p2">
											</div>
										</div>
									</div>
								</div>

								<span class="btn btn-sm btn-warning" id="chg-pw">
									<i class="fa fa-fw fa-lock"></i> &nbsp;
									<span class="txt-ganti"> Ganti Kata Sandi</span>
								</span>
								<span class="btn btn-sm btn-info" id="save-pw" style="display: none;">
									<i class="fa fa-fw fa-check"></i> &nbsp;
									<span class=""> Simpan Kata Sandi</span>
								</span>
							@endif
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

@section('css')
	<meta name="csrf-token" content="{{ csrf_token() }}">
@endsection

@section('js')
	<script src="{{ asset('mdp/js/sweetalert2.js') }}"></script>
	<script>
		$.ajaxSetup({
			headers: {
				'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
			}
		});

		$('#chg-pw').click(function(e){
			e.preventDefault()
		    $(this).find('.fa').toggleClass('fa-times');
		    $(this).find('.fa').toggleClass('fa-lock');
			$('#pw').slideToggle(function(){
				if($('#pw').is(':hidden')){
				  $('.txt-ganti').html('Ganti Kata Sandi')
				}else{
				  $('.txt-ganti').html('Batal')
				}

				$('#save-pw').slideToggle('fast')
			})
		})

		$('#save-pw').click(function(e){
			e.preventDefault()

	        swal({
                title: 'Apakah Anda Yakin?',
                type: 'question',
                showCancelButton: true,
                confirmButtonText: 'Ya',
                cancelButtonText: 'Batal'
	        }).then(function() {
                swal('Mohon Menunggu')
                swal.showLoading()

				var url='{{ route('users.update', ":usr") }}'
				url = url.replace(':usr', '{{ $user->id }}')
				var data= $('#f-pw').serialize()
				$.ajax({
				    url: url,
				    type: 'PUT',
				    data:data,
				    success: function(r) {
				        console.log(r)
				        if(r!='ok'){
				            swal(
				                'Terjadi kesalahan!',
				                'Mohon Dicek Kembali.',
				                'error'
				            )
				        } else {
					        swal(
					            'Berhasil',
					            '',
					            'success'
					        ).then(function() {
					        })
				        }
				    },				    
				}).fail(function(response){
					console.log(response)
					errtext=''
					for(i in response.responseJSON.password){
						errtext+=(response.responseJSON.password[i]=="The password confirmation does not match."?"Konfirmasi kata sandi tidak sama. ":"")
						errtext+=(response.responseJSON.password[i]=="The password must be at least 6 characters."?"Kata sandi minimal 6 karakter. ":"")
					}
			        swal(
			            'Terjadi kesalahan!',
			            errtext,
			            'error'
			        )			    	
				})
      		})


		})

		$('#img').change(function() {
	        swal('Mohon Menunggu')
	        swal.showLoading()

	        old1 = $("#img").data('old')
	        var form_data = new FormData();
	        form_data.append("file", $("#img").prop("files")[0])
	        form_data.append("dir", 'avatar')
	        form_data.append("w", 800)
	        form_data.append("h", 800)

	        $.ajax({
	            url: "{{route('cms-upload') }}",
	            cache: false,
	            contentType: false,
	            processData: false,
	            data: form_data,
	            type: 'post',
	            success: function (p) {
	                if (!p.p1) {
	                    if (old1 != p.p1) {
	                        p.p1 = old1;
	                    }
	                }
	                data = {
	                    idp: "{{ $user->id }}",
	                    p1: p.p1
	                }
	                $.post("{{route('update-profile') }}", data, function (r) {
				        swal(
				            'Berhasil',
				            '',
				            'success'
				        ).then(function() {
			            	// $('#rp').empty().slideReveal("hide")
			           		location.reload(true)
				        })
	                	
	                }, 'json').fail(function (response) {
	                    console.log(response)
	                    swal(
	                        'Terjadi kesalahan!',
	                        //response.responseText,
                            'Mohon Dicek Kembali.',
	                        'error'
	                    )
	                });
	            }
	        })
		})
		
	</script>

@endsection